# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'smekarthick/python-tf-assesment'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8s Dev'
        namespace: 'default'
        command: 'apply'
        arguments: '-f .'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        workingDirectory: '$(Build.SourcesDirectory)/k8sManifests'
        outputFormat: 'yaml'